- tests/DataValues/MonolingualTextValueTest.php
- tests/DataValues/MultilingualTextValueTest.php
Non-optional constructor arguments don't necessarily throw an Exception you can catch in a test, depending on the PHP/HHVM version/configuration they may cause a runtime error instead.
> Fix broken tests

- tests/ValueFormatters/Exceptions/MismatchingDataValueTypeException.php
- tests/ValueFormatters/StringFormatterTest.php
- tests/ValueParsers/BoolParserTest.php
- tests/ValueParsers/FloatParserTest.php
- tests/ValueParsers/IntParserTest.php
- tests/ValueParsers/NullParserTest.php
- tests/ValueParsers/StringValueParserTest.php
- tests/ValueParsers/ValueParserTestBase.php
* Added missing `@covers`.
* Added missing docs.
* Removed some `@since` that don't make much sense in my opinion.
* Used `markTestSkipped` in `NullParserTest`.
* Moved all `getFormatterClass` methods to the top.
* Made `ValueParserTestBase::invalidInputProvider` abstract. A provider that returns an empty array does not work anyway. This will always result in an error.
> Add missing @covers tags

- tests/ValueParsers/StringValueParserTest.php
- tests/ValueParsers/ValueParserTestBase.php
This removes quite some obsolete code.
Originally the goal was to remove the unused newParserOptions method and to simplify the getInstance methods as much as possible. The additional changes are very closely related.
> Simplify options handling

- src/ValueFormatters/Exceptions/MismatchingDataValueTypeException.php
- src/ValueParsers/BoolParser.php
These classes don't have subclasses. `protected` is just meaningless if there are no subclasses.
> Private by default

- tests/ValueParsers/BoolParserTest.php
- tests/ValueParsers/FloatParserTest.php
- tests/ValueParsers/IntParserTest.php
- tests/ValueParsers/NullParserTest.php
- tests/ValueParsers/ValueParserTestBase.php
Just create an instance instead of using PHP's dark magic to turn a string into an object. This makes it much easier for tools to find usages, for example.
> Deprecate getParserClass in favor of getInstance

- Common.php
- README.md
- composer.json
- tests/ValueParsers/ValueParserTestBase.php
Similar to https://github.com/DataValues/Interfaces/pull/10:
Please review #23 (commit 1) first, merge it, then rebase this patch and review it separately. Or even better: Please move this component to Gerrit so I can create an actual chain that's actually reviewable?
Also: Why is this base class in Common while the other is in Interfaces?
Bug: [T92268](https://phabricator.wikimedia.org/T92268)
> Drop ValueParserTestBase::getParserClass

- tests/ValueFormatters/StringFormatterTest.php
See https://github.com/DataValues/Interfaces/pull/9.
Bug: [T92268](https://phabricator.wikimedia.org/T92268)
> Deprecate getFormatterClass in favor of getInstance

- README.md
- src/ValueFormatters/Exceptions/MismatchingDataValueTypeException.php
- tests/ValueParsers/BoolParserTest.php
- tests/ValueParsers/FloatParserTest.php
- tests/ValueParsers/IntParserTest.php
- tests/ValueParsers/StringValueParserTest.php
* Misspelled class name in the release notes and wrong version number in the class.
* Remove non-helpful return tag.
* Add see tags to methods implementing an abstract base.
> Fix mistake in 0.2.2 documentation

- src/ValueFormatters/Exceptions/MismatchingDataValueTypeException.php
- tests/ValueFormatters/Exceptions/MismatchingDataValueTypeExceptionTest.php
It seems this test was never executed. Note the actual bug in the class (the single-quoted `$message`).
> Fix untested MismatchingDataValueTypeException

- tests/ValueParsers/DispatchingValueParserTest.php
Interfaces do not have a constructor.
> Simplify mock building for interfaces

- src/DataValues/MonolingualTextValue.php
This does not change behavior.
* Always use the same order, language first, text second.
* Reduce duplicate code a bit and throw the same exception for both language checks.
> Simplify MonolingualTextValue constructor

- src/ValueParsers/DispatchingValueParser.php
I bumped into this in `wbparsevalue`, and it took me an hour to find where it comes from.
> fix typo "recognitzed" -> "recognized"

- tests/ValueParsers/FloatParserTest.php
It's easier to target the directory, when needed.
> Remove "@group …Test" tags for individual tests

- Common.php
- mediawiki-extension.json
Re-submission of #56. The style is identical to [what we do in Wikibase DataModel](https://github.com/wmde/WikibaseDataModel/blob/master/WikibaseDataModel.php) and other libraries that are not really MediaWiki extensions, but optionally use MediaWiki's extension registration mechanism.
> Convert DataValues Common to extension registration

- .travis.yml
- composer.json
- src/DataValues/MonolingualTextValue.php
- src/DataValues/MultilingualTextValue.php
The bad `array` type hint was added with #50, but never released. So this does not need an immediate release now.
[Bug: T168681](https://phabricator.wikimedia.org/T168681)
> Remove bad array type hint from …::newFromArray constructors

- composer.json
- phpcs.xml
This is a test for the new https://github.com/wmde/WikibaseCodeSniffer. Note that nothing is left in the local phpcs.xml rule set, except very few actual exceptions from the base rule set.
> Use Wikibase's CodeSniffer instead of MediaWiki's

- tests/DataValues/MonolingualTextValueTest.php
- tests/DataValues/MultilingualTextValueTest.php
- tests/ValueFormatters/StringFormatterTest.php
- tests/ValueParsers/BoolParserTest.php
- tests/ValueParsers/FloatParserTest.php
- tests/ValueParsers/IntParserTest.php
- tests/ValueParsers/NullParserTest.php
- tests/ValueParsers/StringValueParserTest.php
This tests simplifies the syntax of existing `@dataProvider`s and adds a bunch of missing test cases to maximize code coverage. With this, only two protected methods in StringValueParser are uncovered.
This conflicts slightly with #51 because in #51 there are no tests for `newFromArray`. I believe it's fine to merge the two patches in whatever order you prefer.
> Add missing tests and simplify providers

- src/ValueParsers/StringValueParser.php
- tests/ValueParsers/ValueParserTestBase.php
I'm also removing duplicate `@since` tags that don't add anything but repeating when the class was introduced.
> Improve the abstract StringValueParser documentation

- src/DataValues/MultilingualTextValue.php
The useful detail that texts are indexed by language codes was not previously documented.
---
I plan to rely on this detail in WikibaseQualityConstraints soon (see [gerrit change 407656](https://gerrit.wikimedia.org/r/407656)), so I would feel more comfortable if this was explicitly documented :)
> Document keys of MultilingualTextValue::getTexts()

- README.md
- src/ValueParsers/Normalizers/TrimmingStringNormalizer.php
- tests/ValueParsers/Normalizers/TrimmingStringNormalizerTest.php
Pinging @brightbyte.
This is a first step. It's possible to either add all regular expressions from `\Wikibase\StringNormalizer` to this class or to a new, similar class.
[Bug: T47925](https://phabricator.wikimedia.org/T47925)
> Add TrimmingStringNormalizer

- Common.php
- README.md
This is a bit of cheating, as the right (tm) thing to do would be to drop support for PHP <5.6 and release it as 0.5. But I'd rather cheat a bit here, and have 1.0.0 as a next release ever done.
> Release 0.4.3

- README.md
- composer.json
Allows for https://github.com/DataValues/Common/pull/84
Wikibase Repo has 3 usages of StringValueParserTest:
https://github.com/wikimedia/mediawiki-extensions-Wikibase/search?q=StringValueParserTest
These can easily be fixed by using a copy of the class
(or better yet: refactoring away from this inheritance abuse pattern).
> Make tests package private

- src/ValueParsers/StringParser.php
- tests/ValueParsers/StringParserTest.php
I would go so far and count this as a bug. No caller of a ValueParser expects this exception. What they expect and properly report to the user is a ParseException.
~~I can see this is not documented in the interface, but~~ (fixed with https://github.com/DataValues/Interfaces/pull/41) is what almost all existing code (callers as well as implementations) does.
Luckily this is entirely irrelevant in production. The way this method is called guarantees the provided value is a string. So this exception was never thrown. I would like to clean up this inconsistency anyway.
> Fix StringParser::parse not throwing expected ParseException

- .travis.yml
- README.md
- composer.json
- src/DataValues/MonolingualTextValue.php
- src/DataValues/MultilingualTextValue.php
- tests/DataValues/MonolingualTextValueTest.php
- tests/DataValues/MultilingualTextValueTest.php
- tests/ValueFormatters/Exceptions/MismatchingDataValueTypeExceptionTest.php
- tests/ValueFormatters/StringFormatterTest.php
- tests/ValueParsers/DispatchingValueParserTest.php
- tests/ValueParsers/Normalizers/NullStringNormalizerTest.php
- tests/ValueParsers/Normalizers/TrimmingStringNormalizerTest.php
- tests/ValueParsers/StringParserTest.php
- tests/ValueParsers/ValueParserTestBase.php
Update PHP versions and dependencies on PHPUnit, DataValues and Interfaces. See individual commit messages for details.
I assume this will fail in CI until the new versions of DataValues and Interfaces have been released – I tested this locally by symlinking my Git checkouts into `vendor/data-values/`.
> Update PHP, PHPUnit, DataValues, Interfaces

- .github/workflows/php.yml
- composer.json
- phpcs.xml
- src/DataValues/MonolingualTextValue.php
- src/ValueFormatters/Exceptions/MismatchingDataValueTypeException.php
- src/ValueParsers/BoolParser.php
- src/ValueParsers/StringParser.php
- src/ValueParsers/StringValueParser.php
- tests/ValueParsers/DispatchingValueParserTest.php
- tests/ValueParsers/NullParserTest.php
- tests/ValueParsers/StringParserTest.php
- tests/ValueParsers/ValueParserTestBase.php
This repository is currently using version 34 of the Mediawiki coding style phpcs rules. If the code aims to comply with Mediawiki style guidelines, it makes sense that it continues to comply at current versions of the rules.
Besides being simply different, the newer versions of the rules introduce, for example,
MediaWiki.Usage.NullableType.ExplicitNullableTypes, which enforces compliance with coming deprecation rules in PHP 8.4 concerning nullable types. If the code does not remove the soon-to-be-deprecated form of nullable type declarations, the library will no longer be usable in Mediawiki for PHP 8.4 deployments.
Resolves #100
Bug: T379481
> Upgrade mediawiki-codesniffer to latest version (45.0.0)

- README.md
* Drop support for PHP 7.2, 7.3
* Upgrade codesniffer rules to current `mediawiki/mediawiki-codesniffer` version (45.0.0)
* Make nullable type parameter declarations explicit for compatibility with PHP 8.4
* Start testing with modern versions of PHP (8.1-8.4)
> Bump version to 1.2.0
